version: 0.2

phases:
  install:
    commands:
      - env
      - curl -fsSL https://raw.githubusercontent.com/thii/aws-codebuild-extras/master/install >> extras.sh
      - . ./extras.sh
  build:
    commands:
      - # Do nothing