version: 0.2

phases:
  install:
    commands:
      - export CODEBUILD_GIT_SHORT_COMMIT="$(git log -1 --pretty=%h)"
      - export CODEBUILD_GIT_MESSAGE="$(git log -1 --pretty=%B)"
      - echo $CODEBUILD_GIT_SHORT_COMMIT
      - echo $CODEBUILD_GIT_MESSAGE
      - echo "Fetching the latest changes..."
      - git fetch origin
      - echo "Detecting changed files between this commit and the previous commit..."
      - git diff --name-only $CODEBUILD_RESOLVED_SOURCE_VERSION~1 $CODEBUILD_RESOLVED_SOURCE_VERSION > changed_files.txt
      - echo "Changed files:"
      - cat changed_files.txt
  build:
    commands:
      - env
      - echo "Checking if 'project' or 'doc' folders were modified..."
      - |
        if grep -q "^project/" changed_files.txt; then
          echo "Changes detected in the project folder. OK"
        fi
      - |
        if grep -q "^vagrant_scripts/" changed_files.txt; then
          echo "Changes detected in the vagrant_scripts folder. OK"
        fi
      - |
        if ! grep -q "^project/" changed_files.txt && ! grep -q "^vagrant_scripts/" changed_files.txt; then
          echo "No changes detected in 'project' or 'doc' folders."
        fi

